[project]
name = 'Digital-Identity-and-Privacy-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.compliance-registry]
path = 'contracts/compliance-registry.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
